#ifndef _WINO_HW_CONFIG_H_
#define _WINO_HW_CONFIG_H_

#define WINO_DOMAIN_SIZE 4
#define INPUT_BUFFER_DEPTH_BITWIDTH 12
#define OUTPUT_BUFFER_DEPTH_BITWIDTH 10
#define WEIGHT_BUFFER_DEPTH_BITWIDTH 10
#define WINO_HEIGHT 2
#define WINO_WIDTH 2
#define INBUFFER_HEIGHT_BITWIDTH 2
#define INDEPTH_MINITILE_SIZE_BITWIDTH 2
#define WINO_W2 2
#define WINO_H2 2
#endif

